[109] Add SparkSwap banners and upgrade ui-kit to v1.2.6
sparkpointio/spark-swap-interface pull request #110
Opened 2022-03-28 11:55 UTC by mativanarquero

References #109 
![s_b](https://user-images.githubusercontent.com/50922758/160392419-78606865-8fd7-4d07-8c75-b6e228686732.gif)
![m_s](https://user-images.githubusercontent.com/50922758/160392452-d50ef74c-4605-4b1c-8fce-52388bcfe8e1.gif)

2022-03-28 13:45 UTC, swengr-janan requested changes
Add spacing

![image](https://user-images.githubusercontent.com/61826995/160411487-d09f8544-6228-41eb-b805-be545f80ccba.png)

2022-03-29 04:41 UTC, mativanarquero commented
> Add spacing
> 
> ![image](https://user-images.githubusercontent.com/61826995/160411487-d09f8544-6228-41eb-b805-be545f80ccba.png)
![u_b](https://user-images.githubusercontent.com/50922758/160534690-a5ee0592-31b8-4754-8c49-eb5c605209a5.gif)
![u_bn](https://user-images.githubusercontent.com/50922758/160534696-664bdd9f-e029-4497-b52e-427caecc498a.gif)

2022-03-29 05:08 UTC, swengr-janan approved these changes
AGITH!

2022-03-29 05:36 UTC, kojiadrianojr approved these changes

2022-03-29 16:04 UTC, merged