Integrate more roadmap information
sparkpointio/spark-swap-interface pull request #279
Opened 2022-06-21 04:30 UTC by kojiadrianojr

Added 2023 onwards roadmap details

2022-06-21 04:34 UTC, swengr-janan requested changes

2022-06-21 04:34 UTC, swengr-janan commented on src/pages/SparkSwapWebsite/config/constants/Roadmap.ts
> +        value: 'SparkChain Blockchain Phase 1: Research and development'
Pa capitalize @kojiadrianojr si 'D' sa development

2022-06-21 04:45 UTC, swengr-janan commented
<img width="378" alt="Screen Shot 2022-06-21 at 12 44 59 PM" src="https://user-images.githubusercontent.com/61826995/174718026-992bef82-f2db-40ce-9626-ac1aa46e1646.png">

Fix typo

2022-06-21 06:35 UTC, kojiadrianojr commented on src/pages/SparkSwapWebsite/config/constants/Roadmap.ts
> +        value: 'SparkChain Blockchain Phase 1: Research and development'
PR updated DeJa Vu @swengr-janan

2022-06-22 01:34 UTC, swengr-janan commented
<img width="357" alt="Screen Shot 2022-06-21 at 3 14 51 PM" src="https://user-images.githubusercontent.com/61826995/174924399-d38db6b7-ae61-4dcd-b27f-25059620a686.png">

additional issue

2022-06-23 03:36 UTC, acirrej approved these changes
![image](https://user-images.githubusercontent.com/102147830/175203486-6ee919fb-5f7a-47cc-a2ea-aacead8fd279.png)
![image](https://user-images.githubusercontent.com/102147830/175203534-8091246f-e0e6-461b-8373-710b7ec3d90b.png)
![image](https://user-images.githubusercontent.com/102147830/175203602-fb8102ec-04b3-4c4d-be6e-525457abd672.png)

Changes fixed on my end @swengr-janan pa final check nalang po

2022-06-23 05:22 UTC, swengr-janan approved these changes
AGITH!

2022-06-23 05:22 UTC, merged