Add carousel and update hero sections
sparkpointio/spark-swap-interface pull request #288
Opened 2022-06-29 10:24 UTC by mativanarquero

Closes #287 

![c_s](https://user-images.githubusercontent.com/50922758/176414350-6e4877b3-b0b3-48e2-aa42-8815ec526baa.gif)
![m_c_s](https://user-images.githubusercontent.com/50922758/176414356-e09768d2-27a8-44cc-9881-0820aeba0f26.gif)

2022-06-29 12:25 UTC, medardm commented on src/pages/SparkSwapWebsite/components/Hero/Hero.tsx
> +  const SparkDeFiNowSwap = () => {
padouble check kaini @kojiadrianojr po

2022-06-29 12:25 UTC, medardm approved these changes
LGTM

2022-06-30 03:31 UTC, swengr-janan requested changes

2022-06-30 03:31 UTC, swengr-janan commented on src/pages/SparkSwapWebsite/components/Hero/Hero.tsx
> +            perpetial, all coming this 2022! <br/>
change to **_perpetual_**

2022-06-30 03:35 UTC, swengr-janan commented
Improve ta din ining carousel bullets @mativanarquero 

Mockup:
<img width="303" alt="Screen Shot 2022-06-30 at 11 35 06 AM" src="https://user-images.githubusercontent.com/61826995/176587288-9508a184-0fec-4a97-8b52-5cde1c41f9d6.png">

Current: 
<img width="194" alt="Screen Shot 2022-06-30 at 11 35 29 AM" src="https://user-images.githubusercontent.com/61826995/176587322-45ce6034-e2d6-42a9-9eeb-f7da5c3170d5.png">

2022-07-01 07:51 UTC, mativanarquero commented
> Improve ta din ining carousel bullets @mativanarquero
> 
> Mockup: <img alt="Screen Shot 2022-06-30 at 11 35 06 AM" width="303" src="https://user-images.githubusercontent.com/61826995/176587288-9508a184-0fec-4a97-8b52-5cde1c41f9d6.png">
> 
> Current: <img alt="Screen Shot 2022-06-30 at 11 35 29 AM" width="194" src="https://user-images.githubusercontent.com/61826995/176587322-45ce6034-e2d6-42a9-9eeb-f7da5c3170d5.png">

PR updated
![c_u](https://user-images.githubusercontent.com/50922758/176850111-dac6eee3-883f-4dad-8d36-3038b751ce0b.gif)

2022-07-01 09:25 UTC, swengr-janan commented
@mativanarquero bakit 4 na items to? Dapat 2 lang kasi duplicate na yung iba
<img width="145" alt="Screen Shot 2022-07-01 at 5 25 41 PM" src="https://user-images.githubusercontent.com/61826995/176867012-bc6f09d3-1182-4f27-abff-6a9008ed2f13.png">

2022-07-01 09:26 UTC, swengr-janan commented
@mativanarquero bakit 4 na items to? Dapat 2 lang kasi duplicate na yung iba
<img width="145" alt="Screen Shot 2022-07-01 at 5 25 41 PM" src="https://user-images.githubusercontent.com/61826995/176867012-bc6f09d3-1182-4f27-abff-6a9008ed2f13.png">

2022-07-04 02:48 UTC, mativanarquero commented
> @mativanarquero bakit 4 na items to? Dapat 2 lang kasi duplicate na yung iba <img alt="Screen Shot 2022-07-01 at 5 25 41 PM" width="145" src="https://user-images.githubusercontent.com/61826995/176867012-bc6f09d3-1182-4f27-abff-6a9008ed2f13.png">

PR updated

2022-07-05 02:23 UTC, swengr-janan approved these changes
AGITH

2022-07-05 02:23 UTC, merged