Bug Fix
sparkpointio/spark-swap-interface pull request #35
Opened 2021-03-29 11:41 UTC by kojiadrianojr

* Default logo no display
* Token logo no display
* Update token list 
* Update Srk Logo
* MetaData temporary information
* Add information on config with SparkPoint socmeds and token info
* Add public image srk and srkdefi

2021-03-29 12:05 UTC, aldrickb approved these changes
LGTTM! Pero wait natin si sir Rico regarding sa metadata if good na si mga phrases.

2021-03-29 12:14 UTC, swengr-janan requested changes
Master Koj, naka redirect pa to sa pancake swap medium site ![image](https://user-images.githubusercontent.com/61826995/112835040-53958200-90cb-11eb-8043-b5ce75c92bfa.jpeg)

2021-03-29 12:32 UTC, swengr-janan approved these changes
Confirmed!

2021-03-29 12:37 UTC, Pseudoman21 approved these changes
Aligned!

2021-03-29 12:45 UTC, harveyjavier approved these changes
Enhanced!

2021-03-30 03:18 UTC, ricoz requested changes
Minor change requests

2021-03-30 03:18 UTC, ricoz commented on public/index.html
> +    <meta name="twitter:image" content="https://srk.finance/" />
Link an image, pwede yung SparkDeFi logo

2021-03-30 03:18 UTC, ricoz commented on public/index.html
> +    <meta name="twitter:description" content="Farm the native coin of SparkSwap with SparkSwap FLP Token" />
Change description to same as content above (Yung may "Refuel your rocket...")

2021-03-30 03:18 UTC, ricoz commented on public/index.html
> +    <meta name="twitter:title" content="🚀 SparkSwap - A new way to defy DeFi exchange on Binance Smart Chan (BSC)" />
Change "A new way to defi" to "The preferred"

2021-03-30 03:38 UTC, kojiadrianojr commented on public/index.html
> +    <meta name="twitter:description" content="Farm the native coin of SparkSwap with SparkSwap FLP Token" />
Sir palitan ko rin po yung G.O.A.T ng "Prodigious"?

2021-03-30 05:47 UTC, ricoz commented on public/index.html
> +    <meta name="twitter:image" content="%PUBLIC_URL%/images/192x192_App_Icon.png" />
Nagagana yan na `%PUBLIC_URL%`?

2021-03-30 11:37 UTC, merged